
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: drpreetyrai/drpreetyrai.github.io


      - name: Setup Pages
        uses: drpreetyrai/drpreetyrai.github.io

      - name: Upload site files
        uses: drpreetyrai/drpreetyrai.github.io
        with:
          path: "."

      - name: Deploy to GitHub Pages
        uses: drpreetyrai/drpreetyrai.github.io





